module logistics where

open import Relation.Binary.PropositionalEquality
open import Relation.Binary
open import Data.List
open import Data.List.Relation.Unary.Any
open import Relation.Nullary using (yes; no; Dec)
open import Level
open import Tactic.Deriving.Eq

data C : Set where
 truck1 truck2 city1 city2 airplane1 airport1 airport2 package1 office1 office2 : C
-- EqC : Eq C
unquoteDecl EqC = deriveEq EqC (quote C)

data R : Set where
  invehicle : C → C → R
  incity : C → C → R
  isat : C → C → R
  location : C → R
  vehicle : C → R
  city : C → R
  airport : C → R
  airplane : C → R
  truck : C → R
  package : C → R
-- EqR : Eq R
unquoteDecl EqR = deriveEq EqR (quote R)

data Action : Set where
  load : C → C → C → Action
  unload : C → C → C → Action
  drive : C → C → C → C → Action
  fly : C → C → C → Action
-- EqAction : Eq Action
unquoteDecl EqAction = deriveEq EqAction (quote Action)

open import Mangle using (mangle)

isDecidable : IsDecEquivalence {zero} {zero} (_≡_ {A = R})
isDecidable = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
 _≟_ = mangle  }

isDEC : IsDecEquivalence {zero} {zero} (_≡_ {A = C})
isDEC = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
  _≟_ = mangle  }

isDECA : IsDecEquivalence {zero} {zero} (_≡_ {A = Action})
isDECA = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
  _≟_ = mangle  }

open import sep_experiment {Action} {R} {C} {isDecidable} {isDEC} {isDECA}

open import Data.Product

Γ₁ : Γ
Γ₁ (load p v l) = (+ , package p) ∷ (+ , vehicle v) ∷ (+ , location l) ∷ (+ , isat v l) ∷ (+ , isat p l) ∷ [] , (+ , isat v l) ∷ (+ , location l) ∷ (+ , vehicle v) ∷ (+ , package p) ∷ (+ , invehicle p v) ∷ (- , isat p l) ∷ []
Γ₁ (unload p v l) = (+ , package p) ∷ (+ , vehicle v) ∷ (+ , location l) ∷ (+ , isat v l) ∷ (+ , invehicle p v) ∷ [] , (+ , isat v l) ∷ (+ , location l) ∷ (+ , vehicle v) ∷ (+ , package p) ∷ (+ , isat p l) ∷ (- , invehicle p v) ∷ []
Γ₁ (drive t1 c l1 l2) = (+ , truck t1) ∷ (+ , city c) ∷ (+ , location l1) ∷ (+ , location l2) ∷ (+ , incity l1 c) ∷ (+ , incity l2 c) ∷ (+ , isat t1 l1) ∷ [] , (+ , incity l2 c) ∷ (+ , incity l1 c) ∷ (+ , location l2) ∷ (+ , location l1) ∷ (+ , city c) ∷ (+ , truck t1) ∷ (+ , isat t1 l2) ∷ (- , isat t1 l1) ∷ []
Γ₁ (fly p a1 a2) = (+ , airplane p) ∷ (+ , airport a1) ∷ (+ , airport a2) ∷ (+ , isat p a1) ∷ [] , (+ , airport a2) ∷ (+ , airport a1) ∷ (+ , airplane p) ∷ (+ , isat p a2) ∷ (- , isat p a1) ∷ []

open Data.Product renaming (_,_ to _↝_)


P : State
P = (+ ↝ (package package1)) ∷ (+ ↝ (vehicle truck1)) ∷ (+ ↝ (vehicle truck2)) ∷ (+ ↝ (vehicle airplane1)) ∷ (+ ↝ (truck truck1)) ∷ (+ ↝ (truck truck2)) ∷ (+ ↝ (airplane airplane1)) ∷ (+ ↝ (city city1)) ∷ (+ ↝ (city city2)) ∷ (+ ↝ (location office1)) ∷ (+ ↝ (location office2)) ∷ (+ ↝ (location airport1)) ∷ (+ ↝ (location airport2)) ∷ (+ ↝ (airport airport1)) ∷ (+ ↝ (airport airport2)) ∷ (+ ↝ (incity airport1 city1)) ∷ (+ ↝ (incity airport2 city2)) ∷ (+ ↝ (incity office1 city1)) ∷ (+ ↝ (incity office2 city2)) ∷ (+ ↝ (isat package1 office1)) ∷ (+ ↝ (isat truck1 airport1)) ∷ (+ ↝ (isat truck2 airport2)) ∷ (+ ↝ (isat airplane1 airport1)) ∷ []

Q : State
Q = (+ ↝ (isat package1 office2)) ∷ []

open import Relation.Nullary.Decidable
open import Data.Unit
P' : State
P' = (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity office1 city1) ∷ (+ , isat package1 office1) ∷ (+ , isat truck1 airport1) ∷ (+ , isat airplane1 airport1) ∷ (+ , truck truck2) ∷ (+ , city city2) ∷ (+ , location airport2) ∷ (+ , location office2) ∷ (+ , incity airport2 city2) ∷ (+ , incity office2 city2) ∷ (+ , isat truck2 airport2) ∷ []

plan : f
plan = (join (join (join (join (join (join (join (join (join (join (join (join (join (join (act (drive  truck2 city2 airport2 office2)) (act (drive  truck1 city1 airport1 office1))) (act (fly  airplane1 airport1 airport2))) (act (load  package1 truck1 office1))) (act (drive  truck1 city1 office1 airport1))) (act (unload  package1 truck1 airport1))) (act (fly  airplane1 airport2 airport1))) (act (load  package1 airplane1 airport1))) (act (fly  airplane1 airport1 airport2))) (act (unload  package1 airplane1 airport2))) (act (drive  truck2 city2 office2 airport2))) (act (load  package1 truck2 airport2))) (act (drive  truck2 city2 airport2 office2))) (act (unload  package1 truck2 office2))) halt)

Derivation : Γ₁ , P ↝ Q ¦ plan
Derivation = weakening P (from-yes (decSub P' P)) tt (halt Q tt
        (from-yes (decSub Q ((- , isat truck2 airport2) ∷ (- , isat package1 airport2) ∷ (- , invehicle package1 airplane1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , isat truck2 office2) ∷ (+ , location office2) ∷ (+ , vehicle truck2) ∷ (+ , package package1) ∷ (+ , isat package1 office2) ∷ (- , invehicle package1 truck2) ∷ [])))
        (composition (from-yes (decSub ((- , isat truck2 airport2) ∷ (- , isat package1 airport2) ∷ (- , invehicle package1 airplane1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , package package1) ∷ (+ , vehicle truck2) ∷ (+ , location office2) ∷ (+ , isat truck2 office2) ∷ (+ , invehicle package1 truck2) ∷ [])
        ((- , isat package1 airport2) ∷ (+ , invehicle package1 truck2) ∷ (- , invehicle package1 airplane1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , incity airport2 city2) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , city city2) ∷ (+ , truck truck2) ∷ (+ , isat truck2 office2) ∷ (- , isat truck2 airport2) ∷ [])))
        (composition (from-yes (decSub ((- , isat package1 airport2) ∷ (+ , invehicle package1 truck2) ∷ (- , invehicle package1 airplane1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity office1 city1) ∷ (+ , truck truck2) ∷ (+ , city city2) ∷ (+ , location airport2) ∷ (+ , location office2) ∷ (+ , incity airport2 city2) ∷ (+ , incity office2 city2) ∷ (+ , isat truck2 airport2) ∷ [])
        ((- , isat truck2 office2) ∷ (- , invehicle package1 airplane1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , isat truck2 airport2) ∷ (+ , location airport2) ∷ (+ , vehicle truck2) ∷ (+ , package package1) ∷ (+ , invehicle package1 truck2) ∷ (- , isat package1 airport2) ∷ [])))
        (composition (from-yes (decSub ((- , isat truck2 office2) ∷ (- , invehicle package1 airplane1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , package package1) ∷ (+ , vehicle truck2) ∷ (+ , location airport2) ∷ (+ , isat truck2 airport2) ∷ (+ , isat package1 airport2) ∷ [])
        ((- , invehicle package1 airplane1) ∷ (+ , isat package1 airport2) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity office1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office2 city2) ∷ (+ , location airport2) ∷ (+ , location office2) ∷ (+ , city city2) ∷ (+ , truck truck2) ∷ (+ , isat truck2 airport2) ∷ (- , isat truck2 office2) ∷ [])))
        (composition (from-yes (decSub ((- , invehicle package1 airplane1) ∷ (+ , isat package1 airport2) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity office1 city1) ∷ (+ , truck truck2) ∷ (+ , city city2) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , incity office2 city2) ∷ (+ , incity airport2 city2) ∷ (+ , isat truck2 office2) ∷ [])
        ((- , isat airplane1 airport1) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , isat airplane1 airport2) ∷ (+ , location airport2) ∷ (+ , vehicle airplane1) ∷ (+ , package package1) ∷ (+ , isat package1 airport2) ∷ (- , invehicle package1 airplane1) ∷ [])))
        (composition (from-yes (decSub ((- , isat airplane1 airport1) ∷ (- , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , package package1) ∷ (+ , vehicle airplane1) ∷ (+ , location airport2) ∷ (+ , isat airplane1 airport2) ∷ (+ , invehicle package1 airplane1) ∷ [])
        ((- , isat package1 airport1) ∷ (+ , invehicle package1 airplane1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , airport airport2) ∷ (+ , airport airport1) ∷ (+ , airplane airplane1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat airplane1 airport1) ∷ [])))
        (composition (from-yes (decSub ((- , isat package1 airport1) ∷ (+ , invehicle package1 airplane1) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , airplane airplane1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , isat airplane1 airport1) ∷ [])
        ((- , isat airplane1 airport2) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , isat airplane1 airport1) ∷ (+ , location airport1) ∷ (+ , vehicle airplane1) ∷ (+ , package package1) ∷ (+ , invehicle package1 airplane1) ∷ (- , isat package1 airport1) ∷ [])))
        (composition (from-yes (decSub ((- , isat airplane1 airport2) ∷ (- , invehicle package1 truck1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , package package1) ∷ (+ , vehicle airplane1) ∷ (+ , location airport1) ∷ (+ , isat airplane1 airport1) ∷ (+ , isat package1 airport1) ∷ [])
        ((- , invehicle package1 truck1) ∷ (+ , isat package1 airport1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , airplane airplane1) ∷ (+ , isat airplane1 airport1) ∷ (- , isat airplane1 airport2) ∷ [])))
        (composition (from-yes (decSub ((- , invehicle package1 truck1) ∷ (+ , isat package1 airport1) ∷ (- , isat truck1 office1) ∷ (+ , isat truck1 airport1) ∷ (- , isat package1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , airplane airplane1) ∷ (+ , airport airport2) ∷ (+ , airport airport1) ∷ (+ , isat airplane1 airport2) ∷ [])
        ((- , isat truck1 office1) ∷ (- , isat package1 office1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , isat truck1 airport1) ∷ (+ , location airport1) ∷ (+ , vehicle truck1) ∷ (+ , package package1) ∷ (+ , isat package1 airport1) ∷ (- , invehicle package1 truck1) ∷ [])))
        (composition (from-yes (decSub ((- , isat truck1 office1) ∷ (- , isat package1 office1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , location airport1) ∷ (+ , isat truck1 airport1) ∷ (+ , invehicle package1 truck1) ∷ [])
        ((- , isat package1 office1) ∷ (+ , invehicle package1 truck1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city2) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport2 city2) ∷ (+ , incity office2 city2) ∷ (+ , incity airport1 city1) ∷ (+ , incity office1 city1) ∷ (+ , location airport1) ∷ (+ , location office1) ∷ (+ , city city1) ∷ (+ , truck truck1) ∷ (+ , isat truck1 airport1) ∷ (- , isat truck1 office1) ∷ [])))
        (composition (from-yes (decSub ((- , isat package1 office1) ∷ (+ , invehicle package1 truck1) ∷ (- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city2) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport2 city2) ∷ (+ , incity office2 city2) ∷ (+ , truck truck1) ∷ (+ , city city1) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , incity office1 city1) ∷ (+ , incity airport1 city1) ∷ (+ , isat truck1 office1) ∷ [])
        ((- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat truck1 airport1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , isat truck1 office1) ∷ (+ , location office1) ∷ (+ , vehicle truck1) ∷ (+ , package package1) ∷ (+ , invehicle package1 truck1) ∷ (- , isat package1 office1) ∷ [])))
        (composition (from-yes (decSub ((- , isat airplane1 airport1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat truck1 airport1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , location office1) ∷ (+ , isat truck1 office1) ∷ (+ , isat package1 office1) ∷ [])
        ((- , isat truck1 airport1) ∷ (+ , isat truck1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , isat package1 office1) ∷ (+ , airport airport2) ∷ (+ , airport airport1) ∷ (+ , airplane airplane1) ∷ (+ , isat airplane1 airport2) ∷ (- , isat airplane1 airport1) ∷ [])))
        (composition (from-yes (decSub ((- , isat truck1 airport1) ∷ (+ , isat truck1 office1) ∷ (- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , truck truck2) ∷ (+ , city city1) ∷ (+ , city city2) ∷ (+ , location office1) ∷ (+ , location office2) ∷ (+ , location airport1) ∷ (+ , location airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity airport2 city2) ∷ (+ , incity office1 city1) ∷ (+ , incity office2 city2) ∷ (+ , isat package1 office1) ∷ (+ , airplane airplane1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , isat airplane1 airport1) ∷ [])
        ((- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city2) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport2 city2) ∷ (+ , incity office2 city2) ∷ (+ , isat package1 office1) ∷ (+ , isat airplane1 airport1) ∷ (+ , incity office1 city1) ∷ (+ , incity airport1 city1) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , city city1) ∷ (+ , truck truck1) ∷ (+ , isat truck1 office1) ∷ (- , isat truck1 airport1) ∷ [])))
        (composition (from-yes (decSub ((- , isat truck2 airport2) ∷ (+ , isat truck2 office2) ∷ (+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck2) ∷ (+ , airplane airplane1) ∷ (+ , city city2) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport2 city2) ∷ (+ , incity office2 city2) ∷ (+ , isat package1 office1) ∷ (+ , isat airplane1 airport1) ∷ (+ , truck truck1) ∷ (+ , city city1) ∷ (+ , location airport1) ∷ (+ , location office1) ∷ (+ , incity airport1 city1) ∷ (+ , incity office1 city1) ∷ (+ , isat truck1 airport1) ∷ [])
        ((+ , package package1) ∷ (+ , vehicle truck1) ∷ (+ , vehicle truck2) ∷ (+ , vehicle airplane1) ∷ (+ , truck truck1) ∷ (+ , airplane airplane1) ∷ (+ , city city1) ∷ (+ , location office1) ∷ (+ , location airport1) ∷ (+ , airport airport1) ∷ (+ , airport airport2) ∷ (+ , incity airport1 city1) ∷ (+ , incity office1 city1) ∷ (+ , isat package1 office1) ∷ (+ , isat truck1 airport1) ∷ (+ , isat airplane1 airport1) ∷ (+ , incity office2 city2) ∷ (+ , incity airport2 city2) ∷ (+ , location office2) ∷ (+ , location airport2) ∷ (+ , city city2) ∷ (+ , truck truck2) ∷ (+ , isat truck2 office2) ∷ (- , isat truck2 airport2) ∷ [])))
        ((frame + (package package1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (isat package1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport1) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))
        ((frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (package package1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (frame + (isat package1 office1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport1) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))
        ((frame - (isat truck1 airport1) (λ z → z) (λ z → z) (frame + (isat truck1 office1) (λ z → z) (λ z → z) (frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (package package1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (frame + (isat package1 office1) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))
        ((frame - (isat airplane1 airport1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport2) (λ z → z) (λ z → z) (frame - (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))
        ((frame - (isat package1 office1) (λ z → z) (λ z → z) (frame + (invehicle package1 truck1) (λ z → z) (λ z → z) (frame - (isat airplane1 airport1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport2) (λ z → z) (λ z → z) (frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (package package1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))
        ((frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame - (isat airplane1 airport1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport2) (λ z → z) (λ z → z) (frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))
        ((frame - (invehicle package1 truck1) (λ z → z) (λ z → z) (frame + (isat package1 airport1) (λ z → z) (λ z → z) (frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (package package1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))
        ((frame - (isat airplane1 airport2) (λ z → z) (λ z → z) (frame - (invehicle package1 truck1) (λ z → z) (λ z → z) (frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))
        ((frame - (isat package1 airport1) (λ z → z) (λ z → z) (frame + (invehicle package1 airplane1) (λ z → z) (λ z → z) (frame - (invehicle package1 truck1) (λ z → z) (λ z → z) (frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (package package1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))
        ((frame - (isat airplane1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 airport1) (λ z → z) (λ z → z) (frame - (invehicle package1 truck1) (λ z → z) (λ z → z) (frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame + (isat truck2 office2) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))
        ((frame - (invehicle package1 airplane1) (λ z → z) (λ z → z) (frame + (isat package1 airport2) (λ z → z) (λ z → z) (frame - (isat airplane1 airport1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport2) (λ z → z) (λ z → z) (frame - (isat package1 airport1) (λ z → z) (λ z → z) (frame - (invehicle package1 truck1) (λ z → z) (λ z → z) (frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame + (package package1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))
        ((frame - (isat truck2 office2) (λ z → z) (λ z → z) (frame - (invehicle package1 airplane1) (λ z → z) (λ z → z) (frame - (isat airplane1 airport1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport2) (λ z → z) (λ z → z) (frame - (isat package1 airport1) (λ z → z) (λ z → z) (frame - (invehicle package1 truck1) (λ z → z) (λ z → z) (frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location office2) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))
        ((frame - (isat package1 airport2) (λ z → z) (λ z → z) (frame + (invehicle package1 truck2) (λ z → z) (λ z → z) (frame - (invehicle package1 airplane1) (λ z → z) (λ z → z) (frame - (isat airplane1 airport1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport2) (λ z → z) (λ z → z) (frame - (isat package1 airport1) (λ z → z) (λ z → z) (frame - (invehicle package1 truck1) (λ z → z) (λ z → z) (frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame + (package package1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle truck2) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))
        ((frame - (isat truck2 airport2) (λ z → z) (λ z → z) (frame - (isat package1 airport2) (λ z → z) (λ z → z) (frame - (invehicle package1 airplane1) (λ z → z) (λ z → z) (frame - (isat airplane1 airport1) (λ z → z) (λ z → z) (frame + (isat airplane1 airport2) (λ z → z) (λ z → z) (frame - (isat package1 airport1) (λ z → z) (λ z → z) (frame - (invehicle package1 truck1) (λ z → z) (λ z → z) (frame - (isat truck1 office1) (λ z → z) (λ z → z) (frame + (isat truck1 airport1) (λ z → z) (λ z → z) (frame - (isat package1 office1) (λ z → z) (λ z → z) (frame + (vehicle truck1) (λ z → z) (λ z → z) (frame + (vehicle airplane1) (λ z → z) (λ z → z) (frame + (truck truck1) (λ z → z) (λ z → z) (frame + (truck truck2) (λ z → z) (λ z → z) (frame + (airplane airplane1) (λ z → z) (λ z → z) (frame + (city city1) (λ z → z) (λ z → z) (frame + (city city2) (λ z → z) (λ z → z) (frame + (location office1) (λ z → z) (λ z → z) (frame + (location airport1) (λ z → z) (λ z → z) (frame + (location airport2) (λ z → z) (λ z → z) (frame + (airport airport1) (λ z → z) (λ z → z) (frame + (airport airport2) (λ z → z) (λ z → z) (frame + (incity airport1 city1) (λ z → z) (λ z → z) (frame + (incity airport2 city2) (λ z → z) (λ z → z) (frame + (incity office1 city1) (λ z → z) (λ z → z) (frame + (incity office2 city2) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))
        )
