module blocksworld2 where

open import Relation.Binary.PropositionalEquality
open import Relation.Binary
open import Data.List
open import Data.List.Relation.Unary.Any
open import Relation.Nullary using (yes; no; Dec)
open import Level
open import Tactic.Deriving.Eq

data C : Set where
 c h a b g d e : C
-- EqC : Eq C
unquoteDecl EqC = deriveEq EqC (quote C)

data R : Set where
  clear : C → R
  on : C → C → R
  ontable : C → R
  holding : C → R
  handempty : R
-- EqR : Eq R
unquoteDecl EqR = deriveEq EqR (quote R)

data Action : Set where
  pickup_from_table : C → Action
  putdown_on_table : C → Action
  pickup_from_stack : C → C → Action
  putdown_on_stack : C → C → Action
-- EqAction : Eq Action
unquoteDecl EqAction = deriveEq EqAction (quote Action)

open import Mangle using (mangle)

isDecidable : IsDecEquivalence {zero} {zero} (_≡_ {A = R})
isDecidable = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
 _≟_ = mangle  }

isDEC : IsDecEquivalence {zero} {zero} (_≡_ {A = C})
isDEC = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
  _≟_ = mangle  }

isDECA : IsDecEquivalence {zero} {zero} (_≡_ {A = Action})
isDECA = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
  _≟_ = mangle  }

open import PCPLogic_no_equality {Action} {R} {C} {isDecidable} {isDEC} {isDECA}

open import Data.Product

Γ₁ : Γ
Γ₁ (pickup_from_table x) = (+ , handempty) ∷ (+ , ontable x) ∷ (+ , clear x) ∷ [] , (+ , clear x) ∷ (- , handempty) ∷ (- , ontable x) ∷ (+ , holding x) ∷ []
Γ₁ (putdown_on_table x) = (+ , holding x) ∷ [] , (- , holding x) ∷ (+ , ontable x) ∷ (+ , handempty) ∷ []
Γ₁ (pickup_from_stack x y) = (+ , on x y) ∷ (+ , clear x) ∷ (+ , handempty) ∷ [] , (+ , clear x) ∷ (- , on x y) ∷ (- , handempty) ∷ (+ , holding x) ∷ (+ , clear y) ∷ []
Γ₁ (putdown_on_stack x y) = (+ , holding x) ∷ (+ , clear y) ∷ [] , (- , holding x) ∷ (- , clear y) ∷ (+ , on x y) ∷ (+ , handempty) ∷ []

open Data.Product renaming (_,_ to _↝_)


P : State
P = (+ ↝ (clear e)) ∷ (+ ↝ (ontable d)) ∷ (+ ↝ (on e g)) ∷ (+ ↝ (on g b)) ∷ (+ ↝ (on b a)) ∷ (+ ↝ (on a h)) ∷ (+ ↝ (on h c)) ∷ (+ ↝ (on c d)) ∷ (+ ↝ (handempty)) ∷ []

Q : State
Q = (+ ↝ (on a g)) ∷ (+ ↝ (on g d)) ∷ (+ ↝ (on d b)) ∷ (+ ↝ (on b c)) ∷ (+ ↝ (on c h)) ∷ (+ ↝ (on h e)) ∷ []

open import Relation.Nullary.Decidable
open import Data.Unit
P' : State
P' = (+ , ontable d) ∷ (+ , on g b) ∷ (+ , on b a) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , on e g) ∷ (+ , clear e) ∷ (+ , handempty) ∷ []

plan : f
plan = (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (act (pickup_from_stack  e g)) (act (putdown_on_table  e))) (act (pickup_from_stack  g b))) (act (putdown_on_table  g))) (act (pickup_from_stack  b a))) (act (putdown_on_table  b))) (act (pickup_from_stack  a h))) (act (putdown_on_table  a))) (act (pickup_from_stack  h c))) (act (putdown_on_stack  h e))) (act (pickup_from_stack  c d))) (act (putdown_on_stack  c h))) (act (pickup_from_table  b))) (act (putdown_on_stack  b c))) (act (pickup_from_table  d))) (act (putdown_on_stack  d b))) (act (pickup_from_table  g))) (act (putdown_on_stack  g d))) (act (pickup_from_table  a))) (act (putdown_on_stack  a g))) halt)

Derivation : Γ₁ , P ↝ Q ¦ plan
Derivation = weakening P (from-yes (decSub P' P)) tt (halt Q tt
        (from-yes (decSub Q ((- , ontable a) ∷ (+ , on g d) ∷ (- , clear d) ∷ (- , holding g) ∷ (- , ontable g) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (- , on e g) ∷ (- , holding a) ∷ (- , clear g) ∷ (+ , on a g) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable a) ∷ (+ , on g d) ∷ (- , clear d) ∷ (- , holding g) ∷ (- , ontable g) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (- , on e g) ∷ (+ , holding a) ∷ (+ , clear g) ∷ [])
        ((+ , on g d) ∷ (- , clear d) ∷ (- , holding g) ∷ (- , ontable g) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (- , on a h) ∷ (- , on b a) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear a) ∷ (- , handempty) ∷ (- , ontable a) ∷ (+ , holding a) ∷ [])))
        (composition (from-yes (decSub ((+ , on g d) ∷ (- , clear d) ∷ (- , holding g) ∷ (- , ontable g) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (- , on a h) ∷ (- , on b a) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , handempty) ∷ (+ , ontable a) ∷ (+ , clear a) ∷ [])
        ((- , ontable g) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (- , holding g) ∷ (- , clear d) ∷ (+ , on g d) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable g) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , holding g) ∷ (+ , clear d) ∷ [])
        ((+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (- , on e g) ∷ (+ , clear g) ∷ (- , handempty) ∷ (- , ontable g) ∷ (+ , holding g) ∷ [])))
        (composition (from-yes (decSub ((+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (- , on e g) ∷ (+ , handempty) ∷ (+ , ontable g) ∷ (+ , clear g) ∷ [])
        ((- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (- , holding d) ∷ (- , clear b) ∷ (+ , on d b) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable d) ∷ (+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , holding d) ∷ (+ , clear b) ∷ [])
        ((+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear d) ∷ (- , handempty) ∷ (- , ontable d) ∷ (+ , holding d) ∷ [])))
        (composition (from-yes (decSub ((+ , on b c) ∷ (- , clear c) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , handempty) ∷ (+ , ontable d) ∷ (+ , clear d) ∷ [])
        ((- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (- , holding b) ∷ (- , clear c) ∷ (+ , on b c) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable b) ∷ (+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (+ , holding b) ∷ (+ , clear c) ∷ [])
        ((+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (+ , clear c) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (+ , clear b) ∷ (- , handempty) ∷ (- , ontable b) ∷ (+ , holding b) ∷ [])))
        (composition (from-yes (decSub ((+ , on c h) ∷ (- , clear h) ∷ (- , holding c) ∷ (+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (+ , clear c) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (+ , handempty) ∷ (+ , ontable b) ∷ (+ , clear b) ∷ [])
        ((+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (+ , clear c) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (- , holding c) ∷ (- , clear h) ∷ (+ , on c h) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear d) ∷ (- , on c d) ∷ (+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (+ , clear c) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (+ , holding c) ∷ (+ , clear h) ∷ [])
        ((+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (+ , clear h) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (+ , clear c) ∷ (- , on c d) ∷ (- , handempty) ∷ (+ , holding c) ∷ (+ , clear d) ∷ [])))
        (composition (from-yes (decSub ((+ , on h e) ∷ (- , clear e) ∷ (- , holding h) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (+ , clear h) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (+ , on c d) ∷ (+ , clear c) ∷ (+ , handempty) ∷ [])
        ((+ , clear c) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (+ , clear h) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (+ , on c d) ∷ (- , holding h) ∷ (- , clear e) ∷ (+ , on h e) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear c) ∷ (- , on h c) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (+ , clear h) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , ontable d) ∷ (+ , on c d) ∷ (+ , holding h) ∷ (+ , clear e) ∷ [])
        ((+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on c d) ∷ (+ , clear h) ∷ (- , on h c) ∷ (- , handempty) ∷ (+ , holding h) ∷ (+ , clear c) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable a) ∷ (- , holding a) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on c d) ∷ (+ , on h c) ∷ (+ , clear h) ∷ (+ , handempty) ∷ [])
        ((+ , clear h) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (- , holding a) ∷ (+ , ontable a) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear h) ∷ (- , on a h) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , holding a) ∷ [])
        ((+ , ontable b) ∷ (- , holding b) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , clear a) ∷ (- , on a h) ∷ (- , handempty) ∷ (+ , holding a) ∷ (+ , clear h) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable b) ∷ (- , holding b) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , on a h) ∷ (+ , clear a) ∷ (+ , handempty) ∷ [])
        ((+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (- , holding b) ∷ (+ , ontable b) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear a) ∷ (- , on b a) ∷ (+ , ontable g) ∷ (- , holding g) ∷ (+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , holding b) ∷ [])
        ((+ , ontable g) ∷ (- , holding g) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , clear b) ∷ (- , on b a) ∷ (- , handempty) ∷ (+ , holding b) ∷ (+ , clear a) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable g) ∷ (- , holding g) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , on b a) ∷ (+ , clear b) ∷ (+ , handempty) ∷ [])
        ((+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on b a) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (- , holding g) ∷ (+ , ontable g) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear b) ∷ (- , on g b) ∷ (+ , ontable e) ∷ (- , holding e) ∷ (+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on b a) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , holding g) ∷ [])
        ((+ , ontable e) ∷ (- , holding e) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on b a) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , clear g) ∷ (- , on g b) ∷ (- , handempty) ∷ (+ , holding g) ∷ (+ , clear b) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable e) ∷ (- , holding e) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on b a) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , on g b) ∷ (+ , clear g) ∷ (+ , handempty) ∷ [])
        ((+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on g b) ∷ (+ , on b a) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (- , holding e) ∷ (+ , ontable e) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear g) ∷ (- , on e g) ∷ (+ , clear e) ∷ (+ , ontable d) ∷ (+ , on g b) ∷ (+ , on b a) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , holding e) ∷ [])
        ((+ , ontable d) ∷ (+ , on g b) ∷ (+ , on b a) ∷ (+ , on a h) ∷ (+ , on h c) ∷ (+ , on c d) ∷ (+ , clear e) ∷ (- , on e g) ∷ (- , handempty) ∷ (+ , holding e) ∷ (+ , clear g) ∷ [])))
        ((frame + (ontable d) (λ z → z) (λ z → z) (frame + (on g b) (λ z → z) (λ z → z) (frame + (on b a) (λ z → z) (λ z → z) (frame + (on a h) (λ z → z) (λ z → z) (frame + (on h c) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt))))))))
        ((frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on g b) (λ z → z) (λ z → z) (frame + (on b a) (λ z → z) (λ z → z) (frame + (on a h) (λ z → z) (λ z → z) (frame + (on h c) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))
        ((frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on b a) (λ z → z) (λ z → z) (frame + (on a h) (λ z → z) (λ z → z) (frame + (on h c) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))
        ((frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on b a) (λ z → z) (λ z → z) (frame + (on a h) (λ z → z) (λ z → z) (frame + (on h c) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))
        ((frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on a h) (λ z → z) (λ z → z) (frame + (on h c) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))
        ((frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on a h) (λ z → z) (λ z → z) (frame + (on h c) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))
        ((frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on h c) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))
        ((frame + (clear h) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on h c) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))
        ((frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))
        ((frame + (clear c) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on c d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))
        ((frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))
        ((frame + (clear d) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear c) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))
        ((frame + (on c h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame + (clear d) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear c) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))
        ((frame - (ontable b) (λ z → z) (λ z → z) (frame + (on c h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame + (clear d) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))
        ((frame + (on b c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on c h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))
        ((frame - (ontable d) (λ z → z) (λ z → z) (frame + (on b c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on c h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame + (clear d) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame + (ontable g) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))
        ((frame + (on d b) (λ z → z) (λ z → z) (frame - (clear b) (λ z → z) (λ z → z) (frame - (holding d) (λ z → z) (λ z → z) (frame - (ontable d) (λ z → z) (λ z → z) (frame + (on b c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on c h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame + (clear d) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))
        ((frame - (ontable g) (λ z → z) (λ z → z) (frame + (on d b) (λ z → z) (λ z → z) (frame - (clear b) (λ z → z) (λ z → z) (frame - (holding d) (λ z → z) (λ z → z) (frame - (ontable d) (λ z → z) (λ z → z) (frame + (on b c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on c h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))
        ((frame + (on g d) (λ z → z) (λ z → z) (frame - (clear d) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (ontable g) (λ z → z) (λ z → z) (frame + (on d b) (λ z → z) (λ z → z) (frame - (clear b) (λ z → z) (λ z → z) (frame - (holding d) (λ z → z) (λ z → z) (frame - (ontable d) (λ z → z) (λ z → z) (frame + (on b c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on c h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))
        ((frame - (ontable a) (λ z → z) (λ z → z) (frame + (on g d) (λ z → z) (λ z → z) (frame - (clear d) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (ontable g) (λ z → z) (λ z → z) (frame + (on d b) (λ z → z) (λ z → z) (frame - (clear b) (λ z → z) (λ z → z) (frame - (holding d) (λ z → z) (λ z → z) (frame - (ontable d) (λ z → z) (λ z → z) (frame + (on b c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on c h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c d) (λ z → z) (λ z → z) (frame + (on h e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h c) (λ z → z) (λ z → z) (frame - (on a h) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on b a) (λ z → z) (λ z → z) (frame - (on g b) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (on e g) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))
        )
