module satellite where

open import Relation.Binary.PropositionalEquality
open import Relation.Binary
open import Data.List
open import Data.List.Relation.Unary.Any
open import Relation.Nullary using (yes; no; Dec)
open import Level
open import Tactic.Deriving.Eq

data C : Set where
 satellite0 instrument0 image1 spectrograph2 thermograph0 star0 groundstation1 groundstation2 phenomenon3 phenomenon4 star5 phenomenon6 : C
-- EqC : Eq C
unquoteDecl EqC = deriveEq EqC (quote C)

data R : Set where
  mode : C → R
  instrument : C → R
  direction : C → R
  satellite : C → R
  calibration_target : C → C → R
  have_image : C → C → R
  calibrated : C → R
  power_on : C → R
  power_avail : C → R
  pointing : C → C → R
  supports : C → C → R
  on_board : C → C → R
-- EqR : Eq R
unquoteDecl EqR = deriveEq EqR (quote R)

data Action : Set where
  turn_to : C → C → C → Action
  switch_on : C → C → Action
  switch_off : C → C → Action
  calibrate : C → C → C → Action
  take_image : C → C → C → C → Action
-- EqAction : Eq Action
unquoteDecl EqAction = deriveEq EqAction (quote Action)

open import Mangle using (mangle)

isDecidable : IsDecEquivalence {zero} {zero} (_≡_ {A = R})
isDecidable = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
 _≟_ = mangle  }

isDEC : IsDecEquivalence {zero} {zero} (_≡_ {A = C})
isDEC = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
  _≟_ = mangle  }

isDECA : IsDecEquivalence {zero} {zero} (_≡_ {A = Action})
isDECA = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
  _≟_ = mangle  }

open import PCPLogic_no_equality {Action} {R} {C} {isDecidable} {isDEC} {isDECA}

open import Data.Product

Γ₁ : Γ
Γ₁ (turn_to s d_new d_prev) = (+ , satellite s) ∷ (+ , direction d_new) ∷ (+ , direction d_prev) ∷ (+ , pointing s d_prev) ∷ [] , (+ , direction d_prev) ∷ (+ , direction d_new) ∷ (+ , satellite s) ∷ (+ , pointing s d_new) ∷ (- , pointing s d_prev) ∷ []
Γ₁ (switch_on i s) = (+ , instrument i) ∷ (+ , satellite s) ∷ (+ , on_board i s) ∷ (+ , power_avail s) ∷ [] , (+ , on_board i s) ∷ (+ , satellite s) ∷ (+ , instrument i) ∷ (+ , power_on i) ∷ (- , calibrated i) ∷ (- , power_avail s) ∷ []
Γ₁ (switch_off i s) = (+ , instrument i) ∷ (+ , satellite s) ∷ (+ , on_board i s) ∷ (+ , power_on i) ∷ [] , (+ , on_board i s) ∷ (+ , satellite s) ∷ (+ , instrument i) ∷ (+ , power_avail s) ∷ (- , power_on i) ∷ []
Γ₁ (calibrate s i d) = (+ , satellite s) ∷ (+ , instrument i) ∷ (+ , direction d) ∷ (+ , on_board i s) ∷ (+ , calibration_target i d) ∷ (+ , pointing s d) ∷ (+ , power_on i) ∷ [] , (+ , power_on i) ∷ (+ , pointing s d) ∷ (+ , calibration_target i d) ∷ (+ , on_board i s) ∷ (+ , direction d) ∷ (+ , instrument i) ∷ (+ , satellite s) ∷ (+ , calibrated i) ∷ []
Γ₁ (take_image s d i m) = (+ , satellite s) ∷ (+ , direction d) ∷ (+ , instrument i) ∷ (+ , mode m) ∷ (+ , calibrated i) ∷ (+ , on_board i s) ∷ (+ , supports i m) ∷ (+ , power_on i) ∷ (+ , pointing s d) ∷ [] , (+ , pointing s d) ∷ (+ , power_on i) ∷ (+ , supports i m) ∷ (+ , on_board i s) ∷ (+ , calibrated i) ∷ (+ , mode m) ∷ (+ , instrument i) ∷ (+ , direction d) ∷ (+ , satellite s) ∷ (+ , have_image d m) ∷ []

open Data.Product renaming (_,_ to _↝_)


P : State
P = (+ ↝ (satellite satellite0)) ∷ (+ ↝ (instrument instrument0)) ∷ (+ ↝ (supports instrument0 thermograph0)) ∷ (+ ↝ (calibration_target instrument0 groundstation2)) ∷ (+ ↝ (on_board instrument0 satellite0)) ∷ (+ ↝ (power_avail satellite0)) ∷ (+ ↝ (pointing satellite0 phenomenon6)) ∷ (+ ↝ (mode image1)) ∷ (+ ↝ (mode spectrograph2)) ∷ (+ ↝ (mode thermograph0)) ∷ (+ ↝ (direction star0)) ∷ (+ ↝ (direction groundstation1)) ∷ (+ ↝ (direction groundstation2)) ∷ (+ ↝ (direction phenomenon3)) ∷ (+ ↝ (direction phenomenon4)) ∷ (+ ↝ (direction star5)) ∷ (+ ↝ (direction phenomenon6)) ∷ []

Q : State
Q = (+ ↝ (have_image phenomenon4 thermograph0)) ∷ (+ ↝ (have_image star5 thermograph0)) ∷ (+ ↝ (have_image phenomenon6 thermograph0)) ∷ []

open import Relation.Nullary.Decidable
open import Data.Unit
P' : State
P' = (+ , instrument instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , power_avail satellite0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , satellite satellite0) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon6) ∷ (+ , pointing satellite0 phenomenon6) ∷ []

plan : f
plan = (join (join (join (join (join (join (join (join (join (act (turn_to  satellite0 groundstation2 phenomenon6)) (act (switch_on  instrument0 satellite0))) (act (calibrate  satellite0 instrument0 groundstation2))) (act (turn_to  satellite0 phenomenon4 groundstation2))) (act (take_image  satellite0 phenomenon4 instrument0 thermograph0))) (act (turn_to  satellite0 star5 phenomenon4))) (act (take_image  satellite0 star5 instrument0 thermograph0))) (act (turn_to  satellite0 phenomenon6 star5))) (act (take_image  satellite0 phenomenon6 instrument0 thermograph0))) halt)

Derivation : Γ₁ , P ↝ Q ¦ plan
Derivation = weakening P (from-yes (decSub P' P)) tt (halt Q tt
        (from-yes (decSub Q ((- , pointing satellite0 star5) ∷ (+ , have_image star5 thermograph0) ∷ (- , pointing satellite0 phenomenon4) ∷ (+ , have_image phenomenon4 thermograph0) ∷ (- , pointing satellite0 groundstation2) ∷ (- , power_avail satellite0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , pointing satellite0 phenomenon6) ∷ (+ , power_on instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , calibrated instrument0) ∷ (+ , mode thermograph0) ∷ (+ , instrument instrument0) ∷ (+ , direction phenomenon6) ∷ (+ , satellite satellite0) ∷ (+ , have_image phenomenon6 thermograph0) ∷ [])))
        (composition (from-yes (decSub ((- , pointing satellite0 star5) ∷ (+ , have_image star5 thermograph0) ∷ (- , pointing satellite0 phenomenon4) ∷ (+ , have_image phenomenon4 thermograph0) ∷ (- , pointing satellite0 groundstation2) ∷ (- , power_avail satellite0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , satellite satellite0) ∷ (+ , direction phenomenon6) ∷ (+ , instrument instrument0) ∷ (+ , mode thermograph0) ∷ (+ , calibrated instrument0) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , power_on instrument0) ∷ (+ , pointing satellite0 phenomenon6) ∷ [])
        ((+ , have_image star5 thermograph0) ∷ (- , pointing satellite0 phenomenon4) ∷ (+ , have_image phenomenon4 thermograph0) ∷ (- , pointing satellite0 groundstation2) ∷ (+ , calibrated instrument0) ∷ (- , power_avail satellite0) ∷ (+ , power_on instrument0) ∷ (+ , instrument instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , satellite satellite0) ∷ (+ , pointing satellite0 phenomenon6) ∷ (- , pointing satellite0 star5) ∷ [])))
        (composition (from-yes (decSub ((+ , have_image star5 thermograph0) ∷ (- , pointing satellite0 phenomenon4) ∷ (+ , have_image phenomenon4 thermograph0) ∷ (- , pointing satellite0 groundstation2) ∷ (+ , calibrated instrument0) ∷ (- , power_avail satellite0) ∷ (+ , power_on instrument0) ∷ (+ , instrument instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , satellite satellite0) ∷ (+ , direction phenomenon6) ∷ (+ , direction star5) ∷ (+ , pointing satellite0 star5) ∷ [])
        ((- , pointing satellite0 phenomenon4) ∷ (+ , have_image phenomenon4 thermograph0) ∷ (- , pointing satellite0 groundstation2) ∷ (- , power_avail satellite0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction phenomenon6) ∷ (+ , pointing satellite0 star5) ∷ (+ , power_on instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , calibrated instrument0) ∷ (+ , mode thermograph0) ∷ (+ , instrument instrument0) ∷ (+ , direction star5) ∷ (+ , satellite satellite0) ∷ (+ , have_image star5 thermograph0) ∷ [])))
        (composition (from-yes (decSub ((- , pointing satellite0 phenomenon4) ∷ (+ , have_image phenomenon4 thermograph0) ∷ (- , pointing satellite0 groundstation2) ∷ (- , power_avail satellite0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction phenomenon6) ∷ (+ , satellite satellite0) ∷ (+ , direction star5) ∷ (+ , instrument instrument0) ∷ (+ , mode thermograph0) ∷ (+ , calibrated instrument0) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , power_on instrument0) ∷ (+ , pointing satellite0 star5) ∷ [])
        ((+ , have_image phenomenon4 thermograph0) ∷ (- , pointing satellite0 groundstation2) ∷ (+ , calibrated instrument0) ∷ (- , power_avail satellite0) ∷ (+ , power_on instrument0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , instrument instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon6) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , satellite satellite0) ∷ (+ , pointing satellite0 star5) ∷ (- , pointing satellite0 phenomenon4) ∷ [])))
        (composition (from-yes (decSub ((+ , have_image phenomenon4 thermograph0) ∷ (- , pointing satellite0 groundstation2) ∷ (+ , calibrated instrument0) ∷ (- , power_avail satellite0) ∷ (+ , power_on instrument0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , instrument instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon6) ∷ (+ , satellite satellite0) ∷ (+ , direction star5) ∷ (+ , direction phenomenon4) ∷ (+ , pointing satellite0 phenomenon4) ∷ [])
        ((- , pointing satellite0 groundstation2) ∷ (- , power_avail satellite0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , pointing satellite0 phenomenon4) ∷ (+ , power_on instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , calibrated instrument0) ∷ (+ , mode thermograph0) ∷ (+ , instrument instrument0) ∷ (+ , direction phenomenon4) ∷ (+ , satellite satellite0) ∷ (+ , have_image phenomenon4 thermograph0) ∷ [])))
        (composition (from-yes (decSub ((- , pointing satellite0 groundstation2) ∷ (- , power_avail satellite0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , satellite satellite0) ∷ (+ , direction phenomenon4) ∷ (+ , instrument instrument0) ∷ (+ , mode thermograph0) ∷ (+ , calibrated instrument0) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , power_on instrument0) ∷ (+ , pointing satellite0 phenomenon4) ∷ [])
        ((+ , calibrated instrument0) ∷ (- , power_avail satellite0) ∷ (+ , power_on instrument0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , instrument instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction phenomenon3) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon4) ∷ (+ , satellite satellite0) ∷ (+ , pointing satellite0 phenomenon4) ∷ (- , pointing satellite0 groundstation2) ∷ [])))
        (composition (from-yes (decSub ((+ , calibrated instrument0) ∷ (- , power_avail satellite0) ∷ (+ , power_on instrument0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , instrument instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction phenomenon3) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , satellite satellite0) ∷ (+ , direction phenomenon4) ∷ (+ , direction groundstation2) ∷ (+ , pointing satellite0 groundstation2) ∷ [])
        ((- , power_avail satellite0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , power_on instrument0) ∷ (+ , pointing satellite0 groundstation2) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , direction groundstation2) ∷ (+ , instrument instrument0) ∷ (+ , satellite satellite0) ∷ (+ , calibrated instrument0) ∷ [])))
        (composition (from-yes (decSub ((- , power_avail satellite0) ∷ (- , pointing satellite0 phenomenon6) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , satellite satellite0) ∷ (+ , instrument instrument0) ∷ (+ , direction groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , pointing satellite0 groundstation2) ∷ (+ , power_on instrument0) ∷ [])
        ((- , pointing satellite0 phenomenon6) ∷ (+ , pointing satellite0 groundstation2) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , satellite satellite0) ∷ (+ , instrument instrument0) ∷ (+ , power_on instrument0) ∷ (- , calibrated instrument0) ∷ (- , power_avail satellite0) ∷ [])))
        (composition (from-yes (decSub ((- , pointing satellite0 phenomenon6) ∷ (+ , pointing satellite0 groundstation2) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction groundstation2) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , instrument instrument0) ∷ (+ , satellite satellite0) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , power_avail satellite0) ∷ [])
        ((+ , instrument instrument0) ∷ (+ , supports instrument0 thermograph0) ∷ (+ , calibration_target instrument0 groundstation2) ∷ (+ , on_board instrument0 satellite0) ∷ (+ , power_avail satellite0) ∷ (+ , mode image1) ∷ (+ , mode spectrograph2) ∷ (+ , mode thermograph0) ∷ (+ , direction star0) ∷ (+ , direction groundstation1) ∷ (+ , direction phenomenon3) ∷ (+ , direction phenomenon4) ∷ (+ , direction star5) ∷ (+ , direction phenomenon6) ∷ (+ , direction groundstation2) ∷ (+ , satellite satellite0) ∷ (+ , pointing satellite0 groundstation2) ∷ (- , pointing satellite0 phenomenon6) ∷ [])))
        ((frame + (instrument instrument0) (λ z → z) (λ z → z) (frame + (supports instrument0 thermograph0) (λ z → z) (λ z → z) (frame + (calibration_target instrument0 groundstation2) (λ z → z) (λ z → z) (frame + (on_board instrument0 satellite0) (λ z → z) (λ z → z) (frame + (power_avail satellite0) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (mode thermograph0) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction phenomenon4) (λ z → z) (λ z → z) (frame + (direction star5) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))
        ((frame - (pointing satellite0 phenomenon6) (λ z → z) (λ z → z) (frame + (pointing satellite0 groundstation2) (λ z → z) (λ z → z) (frame + (supports instrument0 thermograph0) (λ z → z) (λ z → z) (frame + (calibration_target instrument0 groundstation2) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (mode thermograph0) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction groundstation2) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction phenomenon4) (λ z → z) (λ z → z) (frame + (direction star5) (λ z → z) (λ z → z) (frame + (direction phenomenon6) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))
        ((frame - (power_avail satellite0) (λ z → z) (λ z → z) (frame - (pointing satellite0 phenomenon6) (λ z → z) (λ z → z) (frame + (supports instrument0 thermograph0) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (mode thermograph0) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction phenomenon4) (λ z → z) (λ z → z) (frame + (direction star5) (λ z → z) (λ z → z) (frame + (direction phenomenon6) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))
        ((frame + (calibrated instrument0) (λ z → z) (λ z → z) (frame - (power_avail satellite0) (λ z → z) (λ z → z) (frame + (power_on instrument0) (λ z → z) (λ z → z) (frame - (pointing satellite0 phenomenon6) (λ z → z) (λ z → z) (frame + (instrument instrument0) (λ z → z) (λ z → z) (frame + (supports instrument0 thermograph0) (λ z → z) (λ z → z) (frame + (calibration_target instrument0 groundstation2) (λ z → z) (λ z → z) (frame + (on_board instrument0 satellite0) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (mode thermograph0) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction star5) (λ z → z) (λ z → z) (frame + (direction phenomenon6) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))
        ((frame - (pointing satellite0 groundstation2) (λ z → z) (λ z → z) (frame - (power_avail satellite0) (λ z → z) (λ z → z) (frame - (pointing satellite0 phenomenon6) (λ z → z) (λ z → z) (frame + (calibration_target instrument0 groundstation2) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction groundstation2) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction star5) (λ z → z) (λ z → z) (frame + (direction phenomenon6) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))
        ((frame + (have_image phenomenon4 thermograph0) (λ z → z) (λ z → z) (frame - (pointing satellite0 groundstation2) (λ z → z) (λ z → z) (frame + (calibrated instrument0) (λ z → z) (λ z → z) (frame - (power_avail satellite0) (λ z → z) (λ z → z) (frame + (power_on instrument0) (λ z → z) (λ z → z) (frame - (pointing satellite0 phenomenon6) (λ z → z) (λ z → z) (frame + (instrument instrument0) (λ z → z) (λ z → z) (frame + (supports instrument0 thermograph0) (λ z → z) (λ z → z) (frame + (calibration_target instrument0 groundstation2) (λ z → z) (λ z → z) (frame + (on_board instrument0 satellite0) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (mode thermograph0) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction groundstation2) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction phenomenon6) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))
        ((frame - (pointing satellite0 phenomenon4) (λ z → z) (λ z → z) (frame + (have_image phenomenon4 thermograph0) (λ z → z) (λ z → z) (frame - (pointing satellite0 groundstation2) (λ z → z) (λ z → z) (frame - (power_avail satellite0) (λ z → z) (λ z → z) (frame - (pointing satellite0 phenomenon6) (λ z → z) (λ z → z) (frame + (calibration_target instrument0 groundstation2) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction groundstation2) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction phenomenon4) (λ z → z) (λ z → z) (frame + (direction phenomenon6) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))
        ((frame + (have_image star5 thermograph0) (λ z → z) (λ z → z) (frame - (pointing satellite0 phenomenon4) (λ z → z) (λ z → z) (frame + (have_image phenomenon4 thermograph0) (λ z → z) (λ z → z) (frame - (pointing satellite0 groundstation2) (λ z → z) (λ z → z) (frame + (calibrated instrument0) (λ z → z) (λ z → z) (frame - (power_avail satellite0) (λ z → z) (λ z → z) (frame + (power_on instrument0) (λ z → z) (λ z → z) (frame + (instrument instrument0) (λ z → z) (λ z → z) (frame + (supports instrument0 thermograph0) (λ z → z) (λ z → z) (frame + (calibration_target instrument0 groundstation2) (λ z → z) (λ z → z) (frame + (on_board instrument0 satellite0) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (mode thermograph0) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction groundstation2) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction phenomenon4) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))
        ((frame - (pointing satellite0 star5) (λ z → z) (λ z → z) (frame + (have_image star5 thermograph0) (λ z → z) (λ z → z) (frame - (pointing satellite0 phenomenon4) (λ z → z) (λ z → z) (frame + (have_image phenomenon4 thermograph0) (λ z → z) (λ z → z) (frame - (pointing satellite0 groundstation2) (λ z → z) (λ z → z) (frame - (power_avail satellite0) (λ z → z) (λ z → z) (frame + (calibration_target instrument0 groundstation2) (λ z → z) (λ z → z) (frame + (mode image1) (λ z → z) (λ z → z) (frame + (mode spectrograph2) (λ z → z) (λ z → z) (frame + (direction star0) (λ z → z) (λ z → z) (frame + (direction groundstation1) (λ z → z) (λ z → z) (frame + (direction groundstation2) (λ z → z) (λ z → z) (frame + (direction phenomenon3) (λ z → z) (λ z → z) (frame + (direction phenomenon4) (λ z → z) (λ z → z) (frame + (direction star5) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))
        )

world-eval : World
world-eval = ⟦ plan ⟧ (canonical-σ Γ₁) (σα P [])
