module blocksworld3 where

open import Relation.Binary.PropositionalEquality
open import Relation.Binary
open import Data.List
open import Data.List.Relation.Unary.Any
open import Relation.Nullary using (yes; no; Dec)
open import Level
open import Tactic.Deriving.Eq

data C : Set where
 f1 a k h g e d i c j b : C
-- EqC : Eq C
unquoteDecl EqC = deriveEq EqC (quote C)

data R : Set where
  clear : C → R
  on : C → C → R
  ontable : C → R
  holding : C → R
  handempty : R
-- EqR : Eq R
unquoteDecl EqR = deriveEq EqR (quote R)

data Action : Set where
  pickup_from_table : C → Action
  putdown_on_table : C → Action
  pickup_from_stack : C → C → Action
  putdown_on_stack : C → C → Action
-- EqAction : Eq Action
unquoteDecl EqAction = deriveEq EqAction (quote Action)

open import Mangle using (mangle)

isDecidable : IsDecEquivalence {zero} {zero} (_≡_ {A = R})
isDecidable = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
 _≟_ = mangle  }

isDEC : IsDecEquivalence {zero} {zero} (_≡_ {A = C})
isDEC = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
  _≟_ = mangle  }

isDECA : IsDecEquivalence {zero} {zero} (_≡_ {A = Action})
isDECA = record { isEquivalence = record {
  refl = λ {x} → refl ;
  sym = λ x → sym x ;
  trans = trans } ;
  _≟_ = mangle  }

open import PCPLogic_no_equality {Action} {R} {C} {isDecidable} {isDEC} {isDECA}

open import Data.Product

Γ₁ : Γ
Γ₁ (pickup_from_table x) = (+ , handempty) ∷ (+ , ontable x) ∷ (+ , clear x) ∷ [] , (+ , clear x) ∷ (- , handempty) ∷ (- , ontable x) ∷ (+ , holding x) ∷ []
Γ₁ (putdown_on_table x) = (+ , holding x) ∷ [] , (- , holding x) ∷ (+ , ontable x) ∷ (+ , handempty) ∷ []
Γ₁ (pickup_from_stack x y) = (+ , on x y) ∷ (+ , clear x) ∷ (+ , handempty) ∷ [] , (+ , clear x) ∷ (- , on x y) ∷ (- , handempty) ∷ (+ , holding x) ∷ (+ , clear y) ∷ []
Γ₁ (putdown_on_stack x y) = (+ , holding x) ∷ (+ , clear y) ∷ [] , (- , holding x) ∷ (- , clear y) ∷ (+ , on x y) ∷ (+ , handempty) ∷ []

open Data.Product renaming (_,_ to _↝_)


P : State
P = (+ ↝ (clear b)) ∷ (+ ↝ (clear j)) ∷ (+ ↝ (clear c)) ∷ (+ ↝ (ontable i)) ∷ (+ ↝ (ontable d)) ∷ (+ ↝ (ontable e)) ∷ (+ ↝ (on b g)) ∷ (+ ↝ (on g h)) ∷ (+ ↝ (on h k)) ∷ (+ ↝ (on k a)) ∷ (+ ↝ (on a f1)) ∷ (+ ↝ (on f1 i)) ∷ (+ ↝ (on j d)) ∷ (+ ↝ (on c e)) ∷ (+ ↝ (handempty)) ∷ []

Q : State
Q = (+ ↝ (on a j)) ∷ (+ ↝ (on j d)) ∷ (+ ↝ (on d b)) ∷ (+ ↝ (on b h)) ∷ (+ ↝ (on h k)) ∷ (+ ↝ (on k i)) ∷ (+ ↝ (on i f1)) ∷ (+ ↝ (on f1 e)) ∷ (+ ↝ (on e g)) ∷ (+ ↝ (on g c)) ∷ []

open import Relation.Nullary.Decidable
open import Data.Unit
P' : State
P' = (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on b g) ∷ (+ , on g h) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , on c e) ∷ (+ , clear c) ∷ (+ , handempty) ∷ []

plan : f
plan = (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (join (act (pickup_from_stack  c e)) (act (putdown_on_table  c))) (act (pickup_from_stack  b g))) (act (putdown_on_stack  b e))) (act (pickup_from_stack  g h))) (act (putdown_on_stack  g c))) (act (pickup_from_stack  b e))) (act (putdown_on_table  b))) (act (pickup_from_table  e))) (act (putdown_on_stack  e g))) (act (pickup_from_stack  h k))) (act (putdown_on_table  h))) (act (pickup_from_stack  k a))) (act (putdown_on_table  k))) (act (pickup_from_stack  a f1))) (act (putdown_on_table  a))) (act (pickup_from_stack  f1 i))) (act (putdown_on_stack  f1 e))) (act (pickup_from_table  i))) (act (putdown_on_stack  i f1))) (act (pickup_from_table  k))) (act (putdown_on_stack  k i))) (act (pickup_from_table  h))) (act (putdown_on_stack  h k))) (act (pickup_from_table  b))) (act (putdown_on_stack  b h))) (act (pickup_from_stack  j d))) (act (putdown_on_table  j))) (act (pickup_from_table  d))) (act (putdown_on_stack  d b))) (act (pickup_from_table  j))) (act (putdown_on_stack  j d))) (act (pickup_from_table  a))) (act (putdown_on_stack  a j))) halt)

Derivation : Γ₁ , P ↝ Q ¦ plan
Derivation = weakening P (from-yes (decSub P' P)) tt (halt Q tt
        (from-yes (decSub Q ((- , ontable a) ∷ (+ , on j d) ∷ (- , clear d) ∷ (- , holding j) ∷ (- , ontable j) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (- , holding a) ∷ (- , clear j) ∷ (+ , on a j) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable a) ∷ (+ , on j d) ∷ (- , clear d) ∷ (- , holding j) ∷ (- , ontable j) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , holding a) ∷ (+ , clear j) ∷ [])
        ((+ , on j d) ∷ (- , clear d) ∷ (- , holding j) ∷ (- , ontable j) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (- , on a f1) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , clear a) ∷ (- , handempty) ∷ (- , ontable a) ∷ (+ , holding a) ∷ [])))
        (composition (from-yes (decSub ((+ , on j d) ∷ (- , clear d) ∷ (- , holding j) ∷ (- , ontable j) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (- , on a f1) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , handempty) ∷ (+ , ontable a) ∷ (+ , clear a) ∷ [])
        ((- , ontable j) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (- , holding j) ∷ (- , clear d) ∷ (+ , on j d) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable j) ∷ (+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , holding j) ∷ (+ , clear d) ∷ [])
        ((+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , clear d) ∷ (- , on j d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (- , handempty) ∷ (- , ontable j) ∷ (+ , holding j) ∷ [])))
        (composition (from-yes (decSub ((+ , on d b) ∷ (- , clear b) ∷ (- , holding d) ∷ (- , ontable d) ∷ (+ , clear d) ∷ (- , on j d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , handempty) ∷ (+ , ontable j) ∷ (+ , clear j) ∷ [])
        ((- , ontable d) ∷ (+ , ontable j) ∷ (- , holding j) ∷ (+ , clear d) ∷ (- , on j d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (- , holding d) ∷ (- , clear b) ∷ (+ , on d b) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable d) ∷ (+ , ontable j) ∷ (- , holding j) ∷ (+ , clear d) ∷ (- , on j d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , holding d) ∷ (+ , clear b) ∷ [])
        ((+ , ontable j) ∷ (- , holding j) ∷ (- , on j d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , clear d) ∷ (- , handempty) ∷ (- , ontable d) ∷ (+ , holding d) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable j) ∷ (- , holding j) ∷ (- , on j d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , handempty) ∷ (+ , ontable d) ∷ (+ , clear d) ∷ [])
        ((+ , clear d) ∷ (- , on j d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (- , holding j) ∷ (+ , ontable j) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear d) ∷ (- , on j d) ∷ (+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , holding j) ∷ [])
        ((+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , ontable d) ∷ (+ , clear j) ∷ (- , on j d) ∷ (- , handempty) ∷ (+ , holding j) ∷ (+ , clear d) ∷ [])))
        (composition (from-yes (decSub ((+ , on b h) ∷ (- , clear h) ∷ (- , holding b) ∷ (- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , clear j) ∷ (+ , handempty) ∷ [])
        ((- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (- , holding b) ∷ (- , clear h) ∷ (+ , on b h) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable b) ∷ (+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , holding b) ∷ (+ , clear h) ∷ [])
        ((+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , clear b) ∷ (- , handempty) ∷ (- , ontable b) ∷ (+ , holding b) ∷ [])))
        (composition (from-yes (decSub ((+ , on h k) ∷ (- , clear k) ∷ (- , holding h) ∷ (- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , handempty) ∷ (+ , ontable b) ∷ (+ , clear b) ∷ [])
        ((- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (- , holding h) ∷ (- , clear k) ∷ (+ , on h k) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable h) ∷ (+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , holding h) ∷ (+ , clear k) ∷ [])
        ((+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , clear h) ∷ (- , handempty) ∷ (- , ontable h) ∷ (+ , holding h) ∷ [])))
        (composition (from-yes (decSub ((+ , on k i) ∷ (- , clear i) ∷ (- , holding k) ∷ (- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , handempty) ∷ (+ , ontable h) ∷ (+ , clear h) ∷ [])
        ((- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (- , holding k) ∷ (- , clear i) ∷ (+ , on k i) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable k) ∷ (+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , holding k) ∷ (+ , clear i) ∷ [])
        ((+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (+ , clear i) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , clear k) ∷ (- , handempty) ∷ (- , ontable k) ∷ (+ , holding k) ∷ [])))
        (composition (from-yes (decSub ((+ , on i f1) ∷ (- , clear f1) ∷ (- , holding i) ∷ (- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (+ , clear i) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , handempty) ∷ (+ , ontable k) ∷ (+ , clear k) ∷ [])
        ((- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (+ , clear i) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (- , holding i) ∷ (- , clear f1) ∷ (+ , on i f1) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable i) ∷ (+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (+ , clear i) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , holding i) ∷ (+ , clear f1) ∷ [])
        ((+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (+ , clear f1) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , clear i) ∷ (- , handempty) ∷ (- , ontable i) ∷ (+ , holding i) ∷ [])))
        (composition (from-yes (decSub ((+ , on f1 e) ∷ (- , clear e) ∷ (- , holding f1) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (+ , clear f1) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , handempty) ∷ (+ , ontable i) ∷ (+ , clear i) ∷ [])
        ((+ , clear i) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (+ , clear f1) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (- , holding f1) ∷ (- , clear e) ∷ (+ , on f1 e) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear i) ∷ (- , on f1 i) ∷ (+ , ontable a) ∷ (- , holding a) ∷ (+ , clear f1) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , holding f1) ∷ (+ , clear e) ∷ [])
        ((+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , clear f1) ∷ (- , on f1 i) ∷ (- , handempty) ∷ (+ , holding f1) ∷ (+ , clear i) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable a) ∷ (- , holding a) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on j d) ∷ (+ , on f1 i) ∷ (+ , clear f1) ∷ (+ , handempty) ∷ [])
        ((+ , clear f1) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (- , holding a) ∷ (+ , ontable a) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear f1) ∷ (- , on a f1) ∷ (+ , ontable k) ∷ (- , holding k) ∷ (+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , holding a) ∷ [])
        ((+ , ontable k) ∷ (- , holding k) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , clear a) ∷ (- , on a f1) ∷ (- , handempty) ∷ (+ , holding a) ∷ (+ , clear f1) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable k) ∷ (- , holding k) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , on a f1) ∷ (+ , clear a) ∷ (+ , handempty) ∷ [])
        ((+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (- , holding k) ∷ (+ , ontable k) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear a) ∷ (- , on k a) ∷ (+ , ontable h) ∷ (- , holding h) ∷ (+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , holding k) ∷ [])
        ((+ , ontable h) ∷ (- , holding h) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , clear k) ∷ (- , on k a) ∷ (- , handempty) ∷ (+ , holding k) ∷ (+ , clear a) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable h) ∷ (- , holding h) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , on k a) ∷ (+ , clear k) ∷ (+ , handempty) ∷ [])
        ((+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (- , holding h) ∷ (+ , ontable h) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear k) ∷ (- , on h k) ∷ (+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , holding h) ∷ [])
        ((+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , clear h) ∷ (- , on h k) ∷ (- , handempty) ∷ (+ , holding h) ∷ (+ , clear k) ∷ [])))
        (composition (from-yes (decSub ((+ , on e g) ∷ (- , clear g) ∷ (- , holding e) ∷ (- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , on h k) ∷ (+ , clear h) ∷ (+ , handempty) ∷ [])
        ((- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (- , holding e) ∷ (- , clear g) ∷ (+ , on e g) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((- , ontable e) ∷ (+ , ontable b) ∷ (- , holding b) ∷ (+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , holding e) ∷ (+ , clear g) ∷ [])
        ((+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , clear e) ∷ (- , handempty) ∷ (- , ontable e) ∷ (+ , holding e) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable b) ∷ (- , holding b) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , handempty) ∷ (+ , ontable e) ∷ (+ , clear e) ∷ [])
        ((+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (- , holding b) ∷ (+ , ontable b) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear e) ∷ (- , on b e) ∷ (+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , holding b) ∷ [])
        ((+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , clear b) ∷ (- , on b e) ∷ (- , handempty) ∷ (+ , holding b) ∷ (+ , clear e) ∷ [])))
        (composition (from-yes (decSub ((+ , on g c) ∷ (- , clear c) ∷ (- , holding g) ∷ (+ , clear h) ∷ (- , on g h) ∷ (+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , on b e) ∷ (+ , clear b) ∷ (+ , handempty) ∷ [])
        ((+ , clear h) ∷ (- , on g h) ∷ (+ , on b e) ∷ (- , clear e) ∷ (- , holding b) ∷ (+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (- , holding g) ∷ (- , clear c) ∷ (+ , on g c) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear h) ∷ (- , on g h) ∷ (+ , on b e) ∷ (- , clear e) ∷ (- , holding b) ∷ (+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , holding g) ∷ (+ , clear c) ∷ [])
        ((+ , on b e) ∷ (- , clear e) ∷ (- , holding b) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , clear c) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , clear g) ∷ (- , on g h) ∷ (- , handempty) ∷ (+ , holding g) ∷ (+ , clear h) ∷ [])))
        (composition (from-yes (decSub ((+ , on b e) ∷ (- , clear e) ∷ (- , holding b) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , clear c) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , on g h) ∷ (+ , clear g) ∷ (+ , handempty) ∷ [])
        ((+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , clear c) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on g h) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (- , holding b) ∷ (- , clear e) ∷ (+ , on b e) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear g) ∷ (- , on b g) ∷ (+ , ontable c) ∷ (- , holding c) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , clear c) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on g h) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , holding b) ∷ (+ , clear e) ∷ [])
        ((+ , ontable c) ∷ (- , holding c) ∷ (+ , clear e) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , clear c) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on g h) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , clear b) ∷ (- , on b g) ∷ (- , handempty) ∷ (+ , holding b) ∷ (+ , clear g) ∷ [])))
        (composition (from-yes (decSub ((+ , ontable c) ∷ (- , holding c) ∷ (+ , clear e) ∷ (- , on c e) ∷ (+ , clear j) ∷ (+ , clear c) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on g h) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , on b g) ∷ (+ , clear b) ∷ (+ , handempty) ∷ [])
        ((+ , clear e) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , clear c) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on b g) ∷ (+ , on g h) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (- , holding c) ∷ (+ , ontable c) ∷ (+ , handempty) ∷ [])))
        (composition (from-yes (decSub ((+ , clear e) ∷ (- , on c e) ∷ (+ , clear b) ∷ (+ , clear j) ∷ (+ , clear c) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on b g) ∷ (+ , on g h) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , holding c) ∷ [])
        ((+ , clear b) ∷ (+ , clear j) ∷ (+ , ontable i) ∷ (+ , ontable d) ∷ (+ , ontable e) ∷ (+ , on b g) ∷ (+ , on g h) ∷ (+ , on h k) ∷ (+ , on k a) ∷ (+ , on a f1) ∷ (+ , on f1 i) ∷ (+ , on j d) ∷ (+ , clear c) ∷ (- , on c e) ∷ (- , handempty) ∷ (+ , holding c) ∷ (+ , clear e) ∷ [])))
        ((frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame + (on b g) (λ z → z) (λ z → z) (frame + (on g h) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))
        ((frame + (clear e) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (clear c) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame + (on b g) (λ z → z) (λ z → z) (frame + (on g h) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))
        ((frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (clear c) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame + (on g h) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))
        ((frame + (clear g) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (clear c) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame + (on g h) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))
        ((frame + (on b e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (clear c) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))
        ((frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame + (on b e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))
        ((frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))
        ((frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (ontable e) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))
        ((frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame + (clear g) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))
        ((frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))
        ((frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))
        ((frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on k a) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))
        ((frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))
        ((frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on a f1) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))
        ((frame + (ontable k) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))
        ((frame + (clear f1) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (ontable k) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on f1 i) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))
        ((frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (ontable k) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame + (clear e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))
        ((frame + (clear i) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame + (clear f1) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (ontable k) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable i) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))))
        ((frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame + (clear f1) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (ontable k) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))
        ((frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame + (clear i) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (ontable k) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))))))
        ((frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame + (clear i) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))))))
        ((frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (ontable h) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))
        ((frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (clear k) (λ z → z) (λ z → z) (frame - (on h k) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))
        ((frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame + (ontable b) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))
        ((frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame + (clear h) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))
        ((frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))))))))
        ((frame + (on b h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))))
        ((frame + (clear d) (λ z → z) (λ z → z) (frame - (on j d) (λ z → z) (λ z → z) (frame + (on b h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (frame + (ontable d) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))))))))))))
        ((frame + (ontable j) (λ z → z) (λ z → z) (frame - (holding j) (λ z → z) (λ z → z) (frame - (on j d) (λ z → z) (λ z → z) (frame + (on b h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear b) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))))))))))))
        ((frame - (ontable d) (λ z → z) (λ z → z) (frame + (ontable j) (λ z → z) (λ z → z) (frame - (holding j) (λ z → z) (λ z → z) (frame + (clear d) (λ z → z) (λ z → z) (frame - (on j d) (λ z → z) (λ z → z) (frame + (on b h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))))))))
        ((frame + (on d b) (λ z → z) (λ z → z) (frame - (clear b) (λ z → z) (λ z → z) (frame - (holding d) (λ z → z) (λ z → z) (frame - (ontable d) (λ z → z) (λ z → z) (frame + (clear d) (λ z → z) (λ z → z) (frame - (on j d) (λ z → z) (λ z → z) (frame + (on b h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))))))))
        ((frame - (ontable j) (λ z → z) (λ z → z) (frame + (on d b) (λ z → z) (λ z → z) (frame - (clear b) (λ z → z) (λ z → z) (frame - (holding d) (λ z → z) (λ z → z) (frame - (ontable d) (λ z → z) (λ z → z) (frame + (on b h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame + (ontable a) (λ z → z) (λ z → z) (frame - (holding a) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))))))))
        ((frame + (on j d) (λ z → z) (λ z → z) (frame - (clear d) (λ z → z) (λ z → z) (frame - (holding j) (λ z → z) (λ z → z) (frame - (ontable j) (λ z → z) (λ z → z) (frame + (on d b) (λ z → z) (λ z → z) (frame - (clear b) (λ z → z) (λ z → z) (frame - (holding d) (λ z → z) (λ z → z) (frame - (ontable d) (λ z → z) (λ z → z) (frame + (on b h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (frame + (clear j) (λ z → z) (λ z → z) (applyAction tt tt)))))))))))))))))))))))))))))))))))))))))))))))
        ((frame - (ontable a) (λ z → z) (λ z → z) (frame + (on j d) (λ z → z) (λ z → z) (frame - (clear d) (λ z → z) (λ z → z) (frame - (holding j) (λ z → z) (λ z → z) (frame - (ontable j) (λ z → z) (λ z → z) (frame + (on d b) (λ z → z) (λ z → z) (frame - (clear b) (λ z → z) (λ z → z) (frame - (holding d) (λ z → z) (λ z → z) (frame - (ontable d) (λ z → z) (λ z → z) (frame + (on b h) (λ z → z) (λ z → z) (frame - (clear h) (λ z → z) (λ z → z) (frame - (holding b) (λ z → z) (λ z → z) (frame - (ontable b) (λ z → z) (λ z → z) (frame + (on h k) (λ z → z) (λ z → z) (frame - (clear k) (λ z → z) (λ z → z) (frame - (holding h) (λ z → z) (λ z → z) (frame - (ontable h) (λ z → z) (λ z → z) (frame + (on k i) (λ z → z) (λ z → z) (frame - (clear i) (λ z → z) (λ z → z) (frame - (holding k) (λ z → z) (λ z → z) (frame - (ontable k) (λ z → z) (λ z → z) (frame + (on i f1) (λ z → z) (λ z → z) (frame - (clear f1) (λ z → z) (λ z → z) (frame - (holding i) (λ z → z) (λ z → z) (frame - (ontable i) (λ z → z) (λ z → z) (frame + (on f1 e) (λ z → z) (λ z → z) (frame - (clear e) (λ z → z) (λ z → z) (frame - (holding f1) (λ z → z) (λ z → z) (frame - (on f1 i) (λ z → z) (λ z → z) (frame - (on a f1) (λ z → z) (λ z → z) (frame + (clear a) (λ z → z) (λ z → z) (frame - (on k a) (λ z → z) (λ z → z) (frame + (on e g) (λ z → z) (λ z → z) (frame - (clear g) (λ z → z) (λ z → z) (frame - (holding e) (λ z → z) (λ z → z) (frame - (ontable e) (λ z → z) (λ z → z) (frame - (on b e) (λ z → z) (λ z → z) (frame + (on g c) (λ z → z) (λ z → z) (frame - (clear c) (λ z → z) (λ z → z) (frame - (holding g) (λ z → z) (λ z → z) (frame - (on g h) (λ z → z) (λ z → z) (frame - (on b g) (λ z → z) (λ z → z) (frame + (ontable c) (λ z → z) (λ z → z) (frame - (holding c) (λ z → z) (λ z → z) (frame - (on c e) (λ z → z) (λ z → z) (applyAction tt tt))))))))))))))))))))))))))))))))))))))))))))))))
        )
